/*
 * Copyright (c) Atmosphère-NX
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Base table which the other tables use for compression purpose
static const u8 T210b01SdevEmcDvfsTableBase[] = {
    #embed "mtc_tables/combined/_base/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableM4gb03[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableM4gb03/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS4gb01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS4gb01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS1z4gb01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS1z4gb01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS1y8gbY01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS1y8gbY01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableM1a4gb01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableM1a4gb01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableH4gb03[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableH4gb03/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS1y4gbX03[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS1y4gbX03/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableM1y4gb01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableM1y4gb01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS1y4gb01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS1y4gb01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableH1y4gb01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableH1y4gb01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS4gb03[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS4gb03/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS4gbY01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS4gbY01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS1y8gb04[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS1y8gb04/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableH1a4gb01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableH1a4gb01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS1y4gbY01[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS1y4gbY01/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS8gb03[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS8gb03/table.bin"
};

static const u8 T210b01SdevEmcDvfsTableS1y8gbX03[] = {
    #embed "mtc_tables/combined/T210b01SdevEmcDvfsTableS1y8gbX03/table.bin"
};
