/*
 * Copyright (c) Atmosphère-NX
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#pragma once

#include "reg.h"

#define CLK_RST_REG_BITS_MASK(NAME)                                      REG_NAMED_BITS_MASK(CLK_RST_CONTROLLER, NAME)
#define CLK_RST_REG_BITS_VALUE(NAME, VALUE)                              REG_NAMED_BITS_VALUE(CLK_RST_CONTROLLER, NAME, VALUE)
#define CLK_RST_REG_BITS_ENUM(NAME, ENUM)                                REG_NAMED_BITS_ENUM(CLK_RST_CONTROLLER, NAME, ENUM)
#define CLK_RST_REG_BITS_ENUM_SEL(NAME, COND, T, F)                     REG_NAMED_BITS_ENUM_SEL(CLK_RST_CONTROLLER, NAME, COND, T, F)

#define DEFINE_CLK_RST_REG(N,O,W)                   REG_DEFINE_NAMED_REG(CLK_RST_CONTROLLER,N,O,W)
#define DEFINE_CLK_RST_REG_BIT_ENUM(N,O,Z,ONE)      REG_DEFINE_NAMED_BIT_ENUM(CLK_RST_CONTROLLER,N,O,Z,ONE)
#define DEFINE_CLK_RST_REG_TWO_BIT_ENUM(N,O,...)    REG_DEFINE_NAMED_TWO_BIT_ENUM(CLK_RST_CONTROLLER,N,O,__VA_ARGS__)
#define DEFINE_CLK_RST_REG_THREE_BIT_ENUM(N,O,...)  REG_DEFINE_NAMED_THREE_BIT_ENUM(CLK_RST_CONTROLLER,N,O,__VA_ARGS__)
#define DEFINE_CLK_RST_REG_FOUR_BIT_ENUM(N,O,...)   REG_DEFINE_NAMED_FOUR_BIT_ENUM(CLK_RST_CONTROLLER,N,O,__VA_ARGS__)

/*
#define CLK_RST_CONTROLLER_RST_SOURCE            (0x000)

#define CLK_RST_CONTROLLER_CCLK_BURST_POLICY     (0x020)
#define CLK_RST_CONTROLLER_SUPER_CCLK_DIVIDER    (0x024)
#define CLK_RST_CONTROLLER_SCLK_BURST_POLICY     (0x028)
#define CLK_RST_CONTROLLER_SUPER_SCLK_DIVIDER    (0x02C)
#define CLK_RST_CONTROLLER_CLK_SYSTEM_RATE       (0x030)
#define CLK_RST_CONTROLLER_MISC_CLK_ENB          (0x048)
#define CLK_RST_CONTROLLER_OSC_CTRL              (0x050)
#define CLK_RST_CONTROLLER_PLLC_BASE             (0x080)
#define CLK_RST_CONTROLLER_PLLC_OUT              (0x084)
#define CLK_RST_CONTROLLER_PLLC_MISC             (0x088)
#define CLK_RST_CONTROLLER_PLLC_MISC1            (0x08C)
#define CLK_RST_CONTROLLER_PLLM_BASE             (0x090)
#define CLK_RST_CONTROLLER_PLLM_MISC1            (0x098)
#define CLK_RST_CONTROLLER_PLLM_MISC2            (0x09C)
#define CLK_RST_CONTROLLER_PLLD_BASE             (0x0D0)
#define CLK_RST_CONTROLLER_PLLD_MISC1            (0x0D8)
#define CLK_RST_CONTROLLER_PLLD_MISC             (0x0DC)
#define CLK_RST_CONTROLLER_PLLX_BASE             (0x0E0)
#define CLK_RST_CONTROLLER_PLLX_MISC             (0x0E4)
#define CLK_RST_CONTROLLER_CCLKG_BURST_POLICY    (0x368)
#define CLK_RST_CONTROLLER_SUPER_CCLKG_DIVIDER   (0x36C)
#define CLK_RST_CONTROLLER_CCLKLP_BURST_POLICY   (0x370)
#define CLK_RST_CONTROLLER_SUPER_CCLKLP_DIVIDER  (0x374)
#define CLK_RST_CONTROLLER_CPU_SOFTRST_CTRL2     (0x388)
#define CLK_RST_CONTROLLER_PLLX_MISC1            (0x510)
#define CLK_RST_CONTROLLER_PLLX_MISC2            (0x514)
#define CLK_RST_CONTROLLER_PLLX_MISC3            (0x518)
#define CLK_RST_CONTROLLER_SPARE_REG0            (0x55C)
#define CLK_RST_CONTROLLER_PLLC4_BASE            (0x5A4)
#define CLK_RST_CONTROLLER_PLLC_MISC2            (0x5D0)
#define CLK_RST_CONTROLLER_PLLMB_BASE            (0x5E8)
#define CLK_RST_CONTROLLER_PLLMB_MISC1           (0x5EC)
*/

/* Mariko. */
#define CLK_RST_CONTROLLER_PLLM_SS_CFG           (0x774)
#define CLK_RST_CONTROLLER_PLLM_SS_CTRL1         (0x778)
#define CLK_RST_CONTROLLER_PLLM_SS_CTRL2         (0x77C)
#define CLK_RST_CONTROLLER_PLLMB_SS_CFG          (0x780)
#define CLK_RST_CONTROLLER_PLLMB_SS_CTRL1        (0x784)
#define CLK_RST_CONTROLLER_PLLMB_SS_CTRL2        (0x788)

/*
#define CLK_RST_CONTROLLER_LVL2_CLK_GATE_OVRA (0x0F8)
#define CLK_RST_CONTROLLER_LVL2_CLK_GATE_OVRB (0x0FC)
#define CLK_RST_CONTROLLER_LVL2_CLK_GATE_OVRC (0x3A0)
#define CLK_RST_CONTROLLER_LVL2_CLK_GATE_OVRD (0x3A4)
#define CLK_RST_CONTROLLER_LVL2_CLK_GATE_OVRE (0x554)
*/

/* RST_DEVICES */
/*
#define CLK_RST_CONTROLLER_RST_DEVICES_L (0x004)
#define CLK_RST_CONTROLLER_RST_DEVICES_H (0x008)
#define CLK_RST_CONTROLLER_RST_DEVICES_U (0x00C)
#define CLK_RST_CONTROLLER_RST_DEVICES_X (0x28C)
#define CLK_RST_CONTROLLER_RST_DEVICES_Y (0x2A4)
#define CLK_RST_CONTROLLER_RST_DEVICES_V (0x358)
#define CLK_RST_CONTROLLER_RST_DEVICES_W (0x35C)
*/

/* CLK_OUT_ENB */
/*
#define CLK_RST_CONTROLLER_CLK_OUT_ENB_L (0x010)
#define CLK_RST_CONTROLLER_CLK_OUT_ENB_H (0x014)
#define CLK_RST_CONTROLLER_CLK_OUT_ENB_U (0x018)
#define CLK_RST_CONTROLLER_CLK_OUT_ENB_X (0x280)
#define CLK_RST_CONTROLLER_CLK_OUT_ENB_Y (0x298)
#define CLK_RST_CONTROLLER_CLK_OUT_ENB_V (0x360)
#define CLK_RST_CONTROLLER_CLK_OUT_ENB_W (0x364)
*/

/* CLK_SOURCE */
/*
#define CLK_RST_CONTROLLER_CLK_SOURCE_PWM               (0x110)
#define CLK_RST_CONTROLLER_CLK_SOURCE_I2C1              (0x124)
#define CLK_RST_CONTROLLER_CLK_SOURCE_I2C5              (0x128)
#define CLK_RST_CONTROLLER_CLK_SOURCE_DISP1             (0x138)
#define CLK_RST_CONTROLLER_CLK_SOURCE_VI                (0x148)
#define CLK_RST_CONTROLLER_CLK_SOURCE_SDMMC1            (0x150)
#define CLK_RST_CONTROLLER_CLK_SOURCE_SDMMC2            (0x154)
#define CLK_RST_CONTROLLER_CLK_SOURCE_SDMMC4            (0x164)
#define CLK_RST_CONTROLLER_CLK_SOURCE_UARTA             (0x178)
#define CLK_RST_CONTROLLER_CLK_SOURCE_UARTB             (0x17C)
#define CLK_RST_CONTROLLER_CLK_SOURCE_HOST1X            (0x180)
#define CLK_RST_CONTROLLER_CLK_SOURCE_I2C2              (0x198)
#define CLK_RST_CONTROLLER_CLK_SOURCE_EMC               (0x19C)
#define CLK_RST_CONTROLLER_CLK_SOURCE_UARTC             (0x1A0)
#define CLK_RST_CONTROLLER_CLK_SOURCE_I2C3              (0x1B8)
#define CLK_RST_CONTROLLER_CLK_SOURCE_SDMMC3            (0x1BC)
#define CLK_RST_CONTROLLER_CLK_SOURCE_CSITE             (0x1D4)
#define CLK_RST_CONTROLLER_CLK_SOURCE_TSEC              (0x1F4)
#define CLK_RST_CONTROLLER_CLK_SOURCE_MSELECT           (0x3B4)
#define CLK_RST_CONTROLLER_CLK_SOURCE_I2C4              (0x3C4)
#define CLK_RST_CONTROLLER_CLK_SOURCE_ACTMON            (0x3E8)
#define CLK_RST_CONTROLLER_CLK_SOURCE_SOR1              (0x410)
#define CLK_RST_CONTROLLER_CLK_SOURCE_SE                (0x42C)
#define CLK_RST_CONTROLLER_CLK_SOURCE_DSIA_LP           (0x620)
#define CLK_RST_CONTROLLER_CLK_SOURCE_DVFS_REF          (0x62C)
#define CLK_RST_CONTROLLER_CLK_SOURCE_DVFS_SOC          (0x630)
#define CLK_RST_CONTROLLER_CLK_SOURCE_I2C6              (0x65C)
#define CLK_RST_CONTROLLER_CLK_SOURCE_EMC_DLL           (0x664)
#define CLK_RST_CONTROLLER_CLK_SOURCE_UART_FST_MIPI_CAL (0x66C)
#define CLK_RST_CONTROLLER_CLK_SOURCE_SDMMC_LEGACY_TM   (0x694)
#define CLK_RST_CONTROLLER_CLK_SOURCE_NVENC             (0x6A0)
*/
#define CLK_RST_CONTROLLER_CLK_SOURCE_EMC_SAFE          (0x724)


/* RST_DEV_*_SET */
/*
#define CLK_RST_CONTROLLER_RST_DEV_L_SET (0x300)
#define CLK_RST_CONTROLLER_RST_DEV_H_SET (0x308)
#define CLK_RST_CONTROLLER_RST_DEV_U_SET (0x310)
#define CLK_RST_CONTROLLER_RST_DEV_V_SET (0x430)
#define CLK_RST_CONTROLLER_RST_DEV_W_SET (0x438)
#define CLK_RST_CONTROLLER_RST_DEV_X_SET (0x290)
#define CLK_RST_CONTROLLER_RST_DEV_Y_SET (0x2A8)
*/

/* RST_DEV_*_CLR */
/*
#define CLK_RST_CONTROLLER_RST_DEV_L_CLR (0x304)
#define CLK_RST_CONTROLLER_RST_DEV_H_CLR (0x30C)
#define CLK_RST_CONTROLLER_RST_DEV_U_CLR (0x314)
#define CLK_RST_CONTROLLER_RST_DEV_V_CLR (0x434)
#define CLK_RST_CONTROLLER_RST_DEV_W_CLR (0x43C)
#define CLK_RST_CONTROLLER_RST_DEV_X_CLR (0x294)
#define CLK_RST_CONTROLLER_RST_DEV_Y_CLR (0x2AC)
*/

/* CLK_ENB_*_SET */
/*
#define CLK_RST_CONTROLLER_CLK_ENB_L_SET (0x320)
#define CLK_RST_CONTROLLER_CLK_ENB_H_SET (0x328)
#define CLK_RST_CONTROLLER_CLK_ENB_U_SET (0x330)
#define CLK_RST_CONTROLLER_CLK_ENB_V_SET (0x440)
#define CLK_RST_CONTROLLER_CLK_ENB_W_SET (0x448)
#define CLK_RST_CONTROLLER_CLK_ENB_X_SET (0x284)
#define CLK_RST_CONTROLLER_CLK_ENB_Y_SET (0x29C)
*/

/* CLK_ENB_*_CLR */
/*
#define CLK_RST_CONTROLLER_CLK_ENB_L_CLR (0x324)
#define CLK_RST_CONTROLLER_CLK_ENB_H_CLR (0x32C)
#define CLK_RST_CONTROLLER_CLK_ENB_U_CLR (0x334)
#define CLK_RST_CONTROLLER_CLK_ENB_X_CLR (0x288)
#define CLK_RST_CONTROLLER_CLK_ENB_Y_CLR (0x2A0)
#define CLK_RST_CONTROLLER_CLK_ENB_V_CLR (0x444)
#define CLK_RST_CONTROLLER_CLK_ENB_W_CLR (0x44C)
*/

/* RST_*_INDEX */
/*
#define CLK_RST_CONTROLLER_RST_I2C1_INDEX   (0x0C)
#define CLK_RST_CONTROLLER_RST_I2C2_INDEX   (0x16)
#define CLK_RST_CONTROLLER_RST_I2C3_INDEX   (0x03)
#define CLK_RST_CONTROLLER_RST_I2C4_INDEX   (0x07)
#define CLK_RST_CONTROLLER_RST_I2C5_INDEX   (0x0F)
#define CLK_RST_CONTROLLER_RST_I2C6_INDEX   (0x06)

#define CLK_RST_CONTROLLER_RST_PWM_INDEX    (0x11)

#define CLK_RST_CONTROLLER_RST_UARTA_INDEX  (0x06)
#define CLK_RST_CONTROLLER_RST_UARTB_INDEX  (0x07)
#define CLK_RST_CONTROLLER_RST_UARTC_INDEX  (0x17)

#define CLK_RST_CONTROLLER_RST_ACTMON_INDEX (0x17)
*/

/* CLK_ENB_*_INDEX */
/*
#define CLK_RST_CONTROLLER_CLK_ENB_I2C1_INDEX   (0x0C)
#define CLK_RST_CONTROLLER_CLK_ENB_I2C2_INDEX   (0x16)
#define CLK_RST_CONTROLLER_CLK_ENB_I2C3_INDEX   (0x03)
#define CLK_RST_CONTROLLER_CLK_ENB_I2C4_INDEX   (0x07)
#define CLK_RST_CONTROLLER_CLK_ENB_I2C5_INDEX   (0x0F)
#define CLK_RST_CONTROLLER_CLK_ENB_I2C6_INDEX   (0x06)

#define CLK_RST_CONTROLLER_CLK_ENB_PWM_INDEX    (0x11)

#define CLK_RST_CONTROLLER_CLK_ENB_UARTA_INDEX  (0x06)
#define CLK_RST_CONTROLLER_CLK_ENB_UARTB_INDEX  (0x07)
#define CLK_RST_CONTROLLER_CLK_ENB_UARTC_INDEX  (0x17)

#define CLK_RST_CONTROLLER_CLK_ENB_ACTMON_INDEX (0x17)

#define CLK_RST_CONTROLLER_CLK_ENB_DVFS_INDEX (0x1B)

#define CLK_RST_CONTROLLER_CLK_ENB_TZRAM_INDEX (0x1E)

#define CLK_RST_CONTROLLER_CLK_ENB_CACHE2_INDEX (0x1F)
#define CLK_RST_CONTROLLER_CLK_ENB_CRAM2_INDEX (0x18)

#define CLK_RST_CONTROLLER_CLK_ENB_SE_INDEX (0x1F)

#define CLK_RST_CONTROLLER_CLK_ENB_CSITE_INDEX   (0x09)

#define CLK_RST_CONTROLLER_CLK_ENB_HOST1X_INDEX   (0x1C)
#define CLK_RST_CONTROLLER_CLK_ENB_TSEC_INDEX     (0x13)
#define CLK_RST_CONTROLLER_CLK_ENB_SOR0_INDEX     (0x16)
#define CLK_RST_CONTROLLER_CLK_ENB_SOR1_INDEX     (0x17)
#define CLK_RST_CONTROLLER_CLK_ENB_SOR_SAFE_INDEX (0x1E)
#define CLK_RST_CONTROLLER_CLK_ENB_KFUSE_INDEX    (0x08)
*/

/* RST_CPUG_CMPLX_* */
/*
#define CLK_RST_CONTROLLER_RST_CPUG_CMPLX_SET   (0x450)
#define CLK_RST_CONTROLLER_RST_CPUG_CMPLX_CLR   (0x454)
*/

DEFINE_CLK_RST_REG(CLK_SOURCE_EMC_EMC_2X_CLK_DIVISOR, 0, 8);
DEFINE_CLK_RST_REG_THREE_BIT_ENUM(CLK_SOURCE_EMC_EMC_2X_CLK_SRC, 29, PLLM_OUT0, PLLC_OUT0, PLLP_OUT0, CLK_M, PLLM_UD, PLLMB_UD, PLLMB_OUT0, PLLP_UD);

DEFINE_CLK_RST_REG(PLLM_BASE_PLLM_DIVP_B01,   20, 1);
DEFINE_CLK_RST_REG(PLLMB_BASE_PLLMB_DIVP_B01, 20, 1);

DEFINE_CLK_RST_REG_BIT_ENUM(CLK_ENB_X_CLK_ENB_EMC_DLL, 14, DISABLE, ENABLE);
